# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RxSwift_01' do

  # Pods for RxSwift_01
  pod 'SwiftLocation', :git => 'https://github.com/malcommac/SwiftLocation.git'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
  pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'
  pod 'RxSwift', git: 'https://github.com/ReactiveX/RxSwift.git'
  pod 'RxCocoa', git: 'https://github.com/ReactiveX/RxSwift.git'
  pod 'RxDataSources', git: 'https://github.com/RxSwiftCommunity/RxDataSources.git'
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings['SWIFT_VERSION'] = '3.0'
       end
   end
end
